var hierarchy =
[
    [ "McCAD::Tools::FloatingPoint::BinaryDecomposition< F >", "d1/db9/classMcCAD_1_1Tools_1_1FloatingPoint_1_1BinaryDecomposition.html", null ],
    [ "McCAD::Geometry::BoundingBox", "dd/dea/classMcCAD_1_1Geometry_1_1BoundingBox.html", null ],
    [ "McCAD::Geometry::Coord", "dc/d5c/classMcCAD_1_1Geometry_1_1Coord.html", null ],
    [ "McCAD::Geometry::Coord2D", "d0/d07/classMcCAD_1_1Geometry_1_1Coord2D.html", null ],
    [ "McCAD::Geometry::Coord3D", "d3/ddf/classMcCAD_1_1Geometry_1_1Coord3D.html", null ],
    [ "McCAD::Tools::FloatingPoint::DecimalDecomposition< F >", "d0/da2/classMcCAD_1_1Tools_1_1FloatingPoint_1_1DecimalDecomposition.html", null ],
    [ "McCAD::Decomposition::Decompose", "dd/d74/classMcCAD_1_1Decomposition_1_1Decompose.html", null ],
    [ "McCAD::Decomposition::DecomposeSolid", "de/dc3/classMcCAD_1_1Decomposition_1_1DecomposeSolid.html", null ],
    [ "McCAD::Tools::DerivativeUV", "dc/d3c/structMcCAD_1_1Tools_1_1DerivativeUV.html", null ],
    [ "McCAD::Geometry::dimension< Type >", "d7/da6/structMcCAD_1_1Geometry_1_1dimension.html", null ],
    [ "McCAD::Geometry::dimension< Coord >", "d8/dfc/structMcCAD_1_1Geometry_1_1dimension_3_01Coord_01_4.html", null ],
    [ "McCAD::Geometry::dimension< Coord2D >", "d6/dc3/structMcCAD_1_1Geometry_1_1dimension_3_01Coord2D_01_4.html", null ],
    [ "McCAD::Geometry::dimension< Coord3D >", "d6/de5/structMcCAD_1_1Geometry_1_1dimension_3_01Coord3D_01_4.html", null ],
    [ "McCAD::Geometry::Edge", "d4/ddf/classMcCAD_1_1Geometry_1_1Edge.html", null ],
    [ "McCAD::Decomposition::EdgeOnSurface", "dd/dcc/classMcCAD_1_1Decomposition_1_1EdgeOnSurface.html", null ],
    [ "McCAD::Tools::FloatingPoint::enable_if_t<(exponent > 0 &&exponent % 2 !=0)> >", "d3/d3e/structMcCAD_1_1Tools_1_1FloatingPoint_1_1pow_3_01F_00_01base_00_01exponent_00_01typename_01std_1b72a7c99384e6b38e7b1087b2f1246b8.html", null ],
    [ "McCAD::Tools::FloatingPoint::enable_if_t<(exponent > 0 &&exponent % 2==0)> >", "d7/d1f/structMcCAD_1_1Tools_1_1FloatingPoint_1_1pow_3_01F_00_01base_00_01exponent_00_01typename_01std_1a2b69c2a007202816ddfb672ae5f4611.html", null ],
    [ "McCAD::Tools::FloatingPoint::enable_if_t<(exponent< 0)> >", "dc/d9c/structMcCAD_1_1Tools_1_1FloatingPoint_1_1pow_3_01F_00_01base_00_01exponent_00_01typename_01std_1d82a2d6b1221060811eec8f3212877c0.html", null ],
    [ "McCAD::Decomposition::FaceCollision", "d1/d5b/classMcCAD_1_1Decomposition_1_1FaceCollision.html", null ],
    [ "McCAD::Decomposition::GenerateFacesList", "de/d74/classMcCAD_1_1Decomposition_1_1GenerateFacesList.html", null ],
    [ "McCAD::Tools::gpCurveType< curveType >", "dd/dfa/structMcCAD_1_1Tools_1_1gpCurveType.html", null ],
    [ "McCAD::Tools::gpCurveType< GeomAbs_CurveType::GeomAbs_Circle >", "da/dee/structMcCAD_1_1Tools_1_1gpCurveType_3_01GeomAbs__CurveType_1_1GeomAbs__Circle_01_4.html", null ],
    [ "McCAD::Tools::gpCurveType< GeomAbs_CurveType::GeomAbs_Ellipse >", "d2/d1b/structMcCAD_1_1Tools_1_1gpCurveType_3_01GeomAbs__CurveType_1_1GeomAbs__Ellipse_01_4.html", null ],
    [ "McCAD::Tools::gpCurveType< GeomAbs_CurveType::GeomAbs_Hyperbola >", "d8/d05/structMcCAD_1_1Tools_1_1gpCurveType_3_01GeomAbs__CurveType_1_1GeomAbs__Hyperbola_01_4.html", null ],
    [ "McCAD::Tools::gpCurveType< GeomAbs_CurveType::GeomAbs_Line >", "da/d3a/structMcCAD_1_1Tools_1_1gpCurveType_3_01GeomAbs__CurveType_1_1GeomAbs__Line_01_4.html", null ],
    [ "McCAD::Tools::gpCurveType< GeomAbs_CurveType::GeomAbs_Parabola >", "df/dc0/structMcCAD_1_1Tools_1_1gpCurveType_3_01GeomAbs__CurveType_1_1GeomAbs__Parabola_01_4.html", null ],
    [ "McCAD::Tools::gpSurfaceType< surfaceType >", "df/d99/structMcCAD_1_1Tools_1_1gpSurfaceType.html", null ],
    [ "McCAD::Tools::gpSurfaceType< GeomAbs_SurfaceType::GeomAbs_Cone >", "dc/ddc/structMcCAD_1_1Tools_1_1gpSurfaceType_3_01GeomAbs__SurfaceType_1_1GeomAbs__Cone_01_4.html", null ],
    [ "McCAD::Tools::gpSurfaceType< GeomAbs_SurfaceType::GeomAbs_Cylinder >", "d6/ddb/structMcCAD_1_1Tools_1_1gpSurfaceType_3_01GeomAbs__SurfaceType_1_1GeomAbs__Cylinder_01_4.html", null ],
    [ "McCAD::Tools::gpSurfaceType< GeomAbs_SurfaceType::GeomAbs_Plane >", "d1/da4/structMcCAD_1_1Tools_1_1gpSurfaceType_3_01GeomAbs__SurfaceType_1_1GeomAbs__Plane_01_4.html", null ],
    [ "McCAD::Tools::gpSurfaceType< GeomAbs_SurfaceType::GeomAbs_Sphere >", "d8/d95/structMcCAD_1_1Tools_1_1gpSurfaceType_3_01GeomAbs__SurfaceType_1_1GeomAbs__Sphere_01_4.html", null ],
    [ "McCAD::Tools::gpSurfaceType< GeomAbs_SurfaceType::GeomAbs_Torus >", "de/dc6/structMcCAD_1_1Tools_1_1gpSurfaceType_3_01GeomAbs__SurfaceType_1_1GeomAbs__Torus_01_4.html", null ],
    [ "std::hash< McCAD::Geometry::Coord >", "db/d48/structstd_1_1hash_3_01McCAD_1_1Geometry_1_1Coord_01_4.html", null ],
    [ "std::hash< McCAD::Geometry::Coord2D >", "d7/da8/structstd_1_1hash_3_01McCAD_1_1Geometry_1_1Coord2D_01_4.html", null ],
    [ "std::hash< McCAD::Geometry::Coord3D >", "d5/dca/structstd_1_1hash_3_01McCAD_1_1Geometry_1_1Coord3D_01_4.html", null ],
    [ "McCAD::Geometry::Surface::Impl", "d2/d1a/classMcCAD_1_1Geometry_1_1Surface_1_1Impl.html", null ],
    [ "McCAD::Tools::Preprocessor::Impl", "d2/d2a/classMcCAD_1_1Tools_1_1Preprocessor_1_1Impl.html", null ],
    [ "McCAD::Decomposition::DecomposeSolid::Impl", "d5/d45/classMcCAD_1_1Decomposition_1_1DecomposeSolid_1_1Impl.html", null ],
    [ "McCAD::Decomposition::Decompose::Impl", "dd/de9/classMcCAD_1_1Decomposition_1_1Decompose_1_1Impl.html", null ],
    [ "McCAD::Decomposition::SplitSolid::Impl", "d2/d85/classMcCAD_1_1Decomposition_1_1SplitSolid_1_1Impl.html", null ],
    [ "McCAD::Decomposition::SplitSurfaces::Impl", "dd/d9d/classMcCAD_1_1Decomposition_1_1SplitSurfaces_1_1Impl.html", null ],
    [ "McCAD::General::InputData::Impl", "d1/d87/classMcCAD_1_1General_1_1InputData_1_1Impl.html", null ],
    [ "McCAD::Geometry::BoundSurface::Impl", "dd/d85/classMcCAD_1_1Geometry_1_1BoundSurface_1_1Impl.html", null ],
    [ "McCAD::Geometry::BoundSurfaceCyl::Impl", "db/d39/classMcCAD_1_1Geometry_1_1BoundSurfaceCyl_1_1Impl.html", null ],
    [ "McCAD::Geometry::BoundSurfacePlane::Impl", "df/dfe/classMcCAD_1_1Geometry_1_1BoundSurfacePlane_1_1Impl.html", null ],
    [ "McCAD::Geometry::BoundSurfaceTor::Impl", "d7/d5b/classMcCAD_1_1Geometry_1_1BoundSurfaceTor_1_1Impl.html", null ],
    [ "McCAD::Geometry::CYLSolid::Impl", "d4/d93/classMcCAD_1_1Geometry_1_1CYLSolid_1_1Impl.html", null ],
    [ "McCAD::Geometry::MeshTriangle::Impl", "df/d9a/classMcCAD_1_1Geometry_1_1MeshTriangle_1_1Impl.html", null ],
    [ "McCAD::Geometry::PLSolid::Impl", "d7/d68/classMcCAD_1_1Geometry_1_1PLSolid_1_1Impl.html", null ],
    [ "McCAD::Geometry::Solid::Impl", "dd/d07/classMcCAD_1_1Geometry_1_1Solid_1_1Impl.html", null ],
    [ "McCAD::Geometry::TORSolid::Impl", "df/d96/classMcCAD_1_1Geometry_1_1TORSolid_1_1Impl.html", null ],
    [ "McCAD::IO::STEPReader::Impl", "de/d1b/classMcCAD_1_1IO_1_1STEPReader_1_1Impl.html", null ],
    [ "McCAD::IO::STEPWriter::Impl", "db/dca/classMcCAD_1_1IO_1_1STEPWriter_1_1Impl.html", null ],
    [ "McCAD::Geometry::Edge::Impl", "d9/d92/classMcCAD_1_1Geometry_1_1Edge_1_1Impl.html", null ],
    [ "McCAD::General::InputData", "d9/d8a/classMcCAD_1_1General_1_1InputData.html", null ],
    [ "McCAD::detail::Iterator< shapeTag >", "da/d0a/classMcCAD_1_1detail_1_1Iterator.html", null ],
    [ "McCAD::Geometry::MeshTriangle", "d7/d5c/classMcCAD_1_1Geometry_1_1MeshTriangle.html", null ],
    [ "McCAD::Tools::PlaneComparator", "db/d28/classMcCAD_1_1Tools_1_1PlaneComparator.html", null ],
    [ "McCAD::Decomposition::PointOnSurface", "db/d00/classMcCAD_1_1Decomposition_1_1PointOnSurface.html", null ],
    [ "McCAD::Tools::PositionUV", "de/de1/structMcCAD_1_1Tools_1_1PositionUV.html", null ],
    [ "McCAD::Tools::FloatingPoint::pow< F, base, exponent, Enable >", "d4/d3f/structMcCAD_1_1Tools_1_1FloatingPoint_1_1pow.html", null ],
    [ "McCAD::Tools::FloatingPoint::pow< F, base, exponent, typename std::enable_if_t<(exponent==0)> >", "df/d08/structMcCAD_1_1Tools_1_1FloatingPoint_1_1pow_3_01F_00_01base_00_01exponent_00_01typename_01std_12f7624f85b4d53f623906d8eed7f8e3f.html", null ],
    [ "McCAD::Decomposition::Preprocessor", "d1/d40/classMcCAD_1_1Decomposition_1_1Preprocessor.html", null ],
    [ "McCAD::Tools::Preprocessor", "d6/d68/classMcCAD_1_1Tools_1_1Preprocessor.html", null ],
    [ "McCAD::Tools::SenseEvaluator", "d1/d31/classMcCAD_1_1Tools_1_1SenseEvaluator.html", null ],
    [ "McCAD::detail::ShapeView< shapeTag >", "d1/da2/classMcCAD_1_1detail_1_1ShapeView.html", null ],
    [ "McCAD::Geometry::Solid", "d1/d65/classMcCAD_1_1Geometry_1_1Solid.html", [
      [ "McCAD::Geometry::CYLSolid", "dd/daa/classMcCAD_1_1Geometry_1_1CYLSolid.html", null ],
      [ "McCAD::Geometry::PLSolid", "db/d54/classMcCAD_1_1Geometry_1_1PLSolid.html", null ],
      [ "McCAD::Geometry::TORSolid", "d5/d3e/classMcCAD_1_1Geometry_1_1TORSolid.html", null ]
    ] ],
    [ "McCAD::Decomposition::SolidObjConstructor", "da/d1f/classMcCAD_1_1Decomposition_1_1SolidObjConstructor.html", null ],
    [ "McCAD::Decomposition::SolidRebuilder", "d2/d82/classMcCAD_1_1Decomposition_1_1SolidRebuilder.html", null ],
    [ "McCAD::Decomposition::SolidRepairer", "de/d1c/classMcCAD_1_1Decomposition_1_1SolidRepairer.html", null ],
    [ "McCAD::Decomposition::SolidSplitter", "de/dbe/classMcCAD_1_1Decomposition_1_1SolidSplitter.html", null ],
    [ "McCAD::Tools::SolidType", "d3/d81/classMcCAD_1_1Tools_1_1SolidType.html", null ],
    [ "McCAD::Decomposition::SplitSolid", "d5/d5d/classMcCAD_1_1Decomposition_1_1SplitSolid.html", null ],
    [ "McCAD::Decomposition::SplitSurfaces", "d4/de5/classMcCAD_1_1Decomposition_1_1SplitSurfaces.html", null ],
    [ "McCAD::IO::STEPReader", "d2/d30/classMcCAD_1_1IO_1_1STEPReader.html", null ],
    [ "McCAD::IO::STEPWriter", "d0/d9f/classMcCAD_1_1IO_1_1STEPWriter.html", null ],
    [ "McCAD::Geometry::Surface", "d1/d2b/classMcCAD_1_1Geometry_1_1Surface.html", [
      [ "McCAD::Geometry::BoundSurface", "d9/d01/classMcCAD_1_1Geometry_1_1BoundSurface.html", [
        [ "McCAD::Geometry::BoundSurfaceCyl", "d8/ddb/classMcCAD_1_1Geometry_1_1BoundSurfaceCyl.html", null ],
        [ "McCAD::Geometry::BoundSurfacePlane", "d8/dbd/classMcCAD_1_1Geometry_1_1BoundSurfacePlane.html", null ],
        [ "McCAD::Geometry::BoundSurfaceTor", "de/d82/classMcCAD_1_1Geometry_1_1BoundSurfaceTor.html", null ]
      ] ]
    ] ],
    [ "McCAD::Tools::SurfaceComparator", "da/d53/classMcCAD_1_1Tools_1_1SurfaceComparator.html", null ],
    [ "McCAD::Decomposition::SurfaceObjCreator", "d4/dac/classMcCAD_1_1Decomposition_1_1SurfaceObjCreator.html", null ],
    [ "McCAD::Tools::SurfacesFuser", "d5/d31/classMcCAD_1_1Tools_1_1SurfacesFuser.html", null ],
    [ "McCAD::Decomposition::SurfacesMerger", "d3/d8b/classMcCAD_1_1Decomposition_1_1SurfacesMerger.html", null ],
    [ "McCAD::detail::TopClass< shapeTag >", "dc/d26/structMcCAD_1_1detail_1_1TopClass.html", null ],
    [ "McCAD::detail::TopClass< TopAbs_ShapeEnum::TopAbs_COMPOUND >", "d1/d8e/structMcCAD_1_1detail_1_1TopClass_3_01TopAbs__ShapeEnum_1_1TopAbs__COMPOUND_01_4.html", null ],
    [ "McCAD::detail::TopClass< TopAbs_ShapeEnum::TopAbs_COMPSOLID >", "db/da7/structMcCAD_1_1detail_1_1TopClass_3_01TopAbs__ShapeEnum_1_1TopAbs__COMPSOLID_01_4.html", null ],
    [ "McCAD::detail::TopClass< TopAbs_ShapeEnum::TopAbs_EDGE >", "de/d79/structMcCAD_1_1detail_1_1TopClass_3_01TopAbs__ShapeEnum_1_1TopAbs__EDGE_01_4.html", null ],
    [ "McCAD::detail::TopClass< TopAbs_ShapeEnum::TopAbs_FACE >", "d7/dec/structMcCAD_1_1detail_1_1TopClass_3_01TopAbs__ShapeEnum_1_1TopAbs__FACE_01_4.html", null ],
    [ "McCAD::detail::TopClass< TopAbs_ShapeEnum::TopAbs_SHELL >", "d5/d6b/structMcCAD_1_1detail_1_1TopClass_3_01TopAbs__ShapeEnum_1_1TopAbs__SHELL_01_4.html", null ],
    [ "McCAD::detail::TopClass< TopAbs_ShapeEnum::TopAbs_SOLID >", "de/d31/structMcCAD_1_1detail_1_1TopClass_3_01TopAbs__ShapeEnum_1_1TopAbs__SOLID_01_4.html", null ],
    [ "McCAD::detail::TopClass< TopAbs_ShapeEnum::TopAbs_VERTEX >", "d1/dd0/structMcCAD_1_1detail_1_1TopClass_3_01TopAbs__ShapeEnum_1_1TopAbs__VERTEX_01_4.html", null ],
    [ "McCAD::detail::TopClass< TopAbs_ShapeEnum::TopAbs_WIRE >", "d3/d3e/structMcCAD_1_1detail_1_1TopClass_3_01TopAbs__ShapeEnum_1_1TopAbs__WIRE_01_4.html", null ],
    [ "McCAD::Decomposition::TriangleCollision", "d7/dc6/classMcCAD_1_1Decomposition_1_1TriangleCollision.html", null ]
];