message("")
message("-- ============================")
message("-- Locating BOOST C++ Libraries")
message("-- ============================")

if(LINUX_OS)
    if(BOOST_CUSTOM_ROOT)
        set(Boost_FOUND True)
        if(Boost_FOUND AND NOT DEFINED BOOST_INCLUDE_DIRS)
            set(BOOST_INCLUDE_DIRS "${BOOST_CUSTOM_ROOT}")
            include_directories(${BOOST_INCLUDE_DIRS})
        endif()
        if(Boost_FOUND AND NOT DEFINED BOOST_LIBRARY_DIRS)
            set(BOOST_LIBRARY_DIRS "${BOOST_CUSTOM_ROOT}/libs")
        endif()
    else()
        find_package(Boost 1.78 REQUIRED)
        if(Boost_FOUND AND NOT DEFINED BOOST_INCLUDE_DIRS)
            set(BOOST_INCLUDE_DIRS ${Boost_INCLUDE_DIRS})
            include_directories(${BOOST_INCLUDE_DIRS})
        endif()
        if(Boost_FOUND AND NOT DEFINED BOOST_LIBRARY_DIRS)
            set(BOOST_LIBRARY_DIRS "${Boost_INCLUDE_DIRS}/../lib")
        endif()
    endif()

    if(Boost_FOUND)
        if(BUILD_SHARED)
            set(BOOST_LIBRARIES_SHARED "")
            foreach (Boost_lib ${Boost_LIBRARIES})
                set(BOOST_LIB "BOOST_LIB-NOTFOUND")
                find_library(BOOST_LIB
                    NAMES ${Boost_lib}
                    HINTS ${BOOST_LIBRARY_DIRS}
                    NO_DEFAULT_PATH)
                list(APPEND BOOST_LIBRARIES_SHARED ${BOOST_LIB})
            endforeach ()
        endif()
        if(BUILD_STATIC)
            set(BOOST_LIBRARIES_STATIC "")
            foreach (Boost_lib ${Boost_LIBRARIES})
                set(BOOST_LIB "BOOST_LIB-NOTFOUND")
                find_library(BOOST_LIB
                    NAMES ${Boost_lib}
                    HINTS ${BOOST_LIBRARY_DIRS}
                    NO_DEFAULT_PATH)
                list(APPEND BOOST_LIBRARIES_STATIC ${BOOST_LIB})
            endforeach ()
        endif()
    endif()
else(LINUX_OS)
    if(DEFINED BOOST_CUSTOM_ROOT)
        set(Boost_FOUND True)
    else()
        message(FATAL_ERROR "BOOST_CUSTOM_PATH is not defined!")
    endif()

    if(Boost_FOUND AND NOT DEFINED BOOST_INCLUDE_DIRS)
        set(BOOST_INCLUDE_DIRS ${BOOST_CUSTOM_ROOT})
        include_directories(${BOOST_INCLUDE_DIRS})
    endif()
    if(Boost_FOUND AND NOT DEFINED BOOST_LIBRARY_DIRS)
        set(BOOST_LIBRARY_DIRS "${BOOST_CUSTOM_ROOT}/libs")
    endif()
endif()

message(STATUS "BOOST_INCLUDE_DIRS: ${BOOST_INCLUDE_DIRS}")
message(STATUS "BOOST_LIBRARY_DIRS: ${BOOST_LIBRARY_DIRS}")
if (BUILD_SHARED)
    message(STATUS "BOOST_LIBRARIES_SHARED: ${BOOST_LIBRARIES_SHARED}")
endif()
if (BUILD_STATIC)
    message(STATUS "BOOST_LIBRARIES_STATIC: ${BOOST_LIBRARIES_STATIC}")
endif()
message("")

